name: release-notes

on:
  push:
    paths-ignore:
  release:
    types: [published]

jobs:

  build:
    if: github.event_name == 'release'
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 0

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v1.7.2
      with:
        commitMode: true
        configuration: ".release_note_conf.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        echo ${{steps.github_release.outputs.changelog}}
        echo ${{steps.github_release.outputs.failed}}

    - uses: meeDamian/github-release@2.0
      with:
        allow_override: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: ${{steps.github_release.outputs.changelog}}
