name: release-notes

on:
  push:
    paths-ignore:
  release:
    types: [published]

jobs:

  build:
    #if: github.event_name == 'release'
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 0

    - name: Tag name
      id: tag_name
      run: |
        GIT_TAG=${{ github.ref }}
        GIT_TAG=${GIT_TAG#refs/tags/}
        echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
        echo "::set-output name=git_tag::${GIT_TAG}"

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v1
      with:
        commitMode: true
        configuration: ".release_note_conf.json"
        toTag: ${{steps.tag_name.outputs.git_tag}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Preview release notes
      run: |
        cat << EOF
        ${{steps.github_release.outputs.changelog}}
        EOF

    - name: Write release notes
      uses: meeDamian/github-release@2.0
      if: github.event_name == 'release'
      with:
        allow_override: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: ${{steps.github_release.outputs.changelog}}
