name: release-notes

on:
  push:
    paths-ignore:
  release:
    types: [published]

jobs:

  build:
    #if: github.event_name == 'release'
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 0

    - name: Tag name
      run: |
        GIT_TAG=${{ github.ref }}
        GIT_TAG=${GIT_TAG#refs/tags/}
        echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV

    - run: echo ${GIT_TAG}

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v1.7.2
      with:
        commitMode: true
        configuration: ".release_note_conf.json"
        toTag: ${TAG}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${GIT_TAG}

    - name: Preview release notes
      run: |
        cat << EOF
        ${{steps.github_release.outputs.changelog}}
        EOF

    - name: Write release notes
      uses: meeDamian/github-release@2.0
      if: github.event_name == 'release'
      with:
        allow_override: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: ${{steps.github_release.outputs.changelog}}

    # - name: Preview Changelog
    #   if: github.event_name != 'release'
    #   id: github_release_preview
    #   uses: mikepenz/release-changelog-builder-action@v1.7.2
    #   with:
    #     commitMode: true
    #     configuration: ".release_note_conf.json"
    #     toTag: "HEAD"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Preview release notes
    #   if: github.event_name != 'release'
    #   run: |
    #     cat << EOF
    #     ${{steps.github_release_preview.outputs.changelog}}
    #     EOF

    # - name: Build Changelog
    #   if: github.event_name == 'release'
    #   id: github_release
    #   uses: mikepenz/release-changelog-builder-action@v1.7.2
    #   with:
    #     commitMode: true
    #     configuration: ".release_note_conf.json"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Write release notes
    #   uses: meeDamian/github-release@2.0
    #   if: github.event_name == 'release'
    #   with:
    #     allow_override: true
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     body: ${{steps.github_release.outputs.changelog}}
